### ISSUE TITLE
64 bit ASM

### ISSUE THREAD

**Issue by ed-miller** [gildor2/fast_zlib#2]
Hi Konstantin,

your work is a great improvement to compression.
Can you port the match32.asm to 64 bit?

Yours Sincerly
Ed

**Comment by gildor2** [comment]
Hi Ed.

I've added test application, and tested C and ASM versions of the library. Also tested how it works in 32 and 64 bits. I can say that
1. Everything works well.
2. ASM provides minimal benefit over C version.

So I'd recommend you using C version instead. Not sure if it is worth supporting ASM version anymore. Perhaps such a little difference is a result of mayor optimizations in Visual C++ compiler compared to what I had 10+ years ago, when performed older tests.

Check Test/deflate_stub.c to see how C code could be replaced with no changes to original zlib code: you should remove deflate.c from build and use deflate_stub.c instead.

I have some plans for further improvement of "match" functionality, so stay tuned :)

Best regards,
Konstantin
