### ISSUE TITLE
[question] Description of the algorithm

### ISSUE THREAD

**Issue by euccas** [gildor2/fast_zlib#4]
@gildor2 

Hi Konstantin,

I have tested your fast-longest-match with the data set I need compress, and fast-longest-match does outperforms the original zlib in terms of speed. I want to understand how it works and so I read your brief description of the algorithm and checked the source code. Now I still have a few questions about your algorithm, could you help me better understand it? 

> When algorithm finds a match (intermediate one), it computes hashes for all matching bytes, and selects a different hash chain - that one which points farther from current position. ...

**Q1**: Do you mean when finding a match, the algorithm computes hashes for *every 3 bytes* in the matching string? Then I think when these hash values are inserted into the hash table ```head[]``` (or the ```prev[]``` if ```head[x]``` already exists, they will fall into different positions. Is my understanding correct?

**Q2**: Regarding to "select a different hash chain - that one which points farther from current position. If we have 2 hash chains, one points at distance 10, and another one at distance 1000, it is not worth checking distance 10 because other bytes will not match ..."
* What do you mean when you refer to "hash chain"? Do you mean the elements in ```prev[]```, eg. checking ```prev[1000]``` betters checking ```prev[100]```?
* When you say "it not worth checking distance 10 because other bytes will not match", my understanding is like the following case:

```
current position 1100, string: abcdabcd......
position 1000, string: abcdabcd......
position 100, string: abcdabcd.......
```
Here we can check the string starting on position 100, because the possible match length is 1000+. If checking position 1000, the possible match length is 100+.
Is this what you mean?

**Q3**: To this piece of code:

```C
cur_match -= offset;
offset = 0;
next_pos = cur_match;
for (i = 0; i <= len - MIN_MATCH; i++) {
    pos = prev[(cur_match + i) & wmask];
    if (pos < next_pos) {
        /* this hash chain is more distant, use it */
        next_pos = pos;
        offset = i;
    } 
}
/* Switch cur_match to next_pos chain */
cur_match = next_pos;
```

I think this piece of code implements the magic "jumping to the hash chain which points to farther distance". I don't quite understand what it tries to do though. Looks to me it does something like this:

```
when a matching string "abcdefg" at position 1000 is found, try to find a longest match, such as "abcdefg123456"
- if prev[1000] exists, record prev[1000] as p1 (a farther position with the same match, using hash value of "abc")
- if prev[1001] ("bcd") exists, record prev[1001] as p2
- if p2 < p1, record next_pos = p2
- do similar thing for prev[1002] ("cde"), prev[1003] ("def"), prev[1004] ("efg"), find the *farthest* next_pos 
```

Is this process the one you mentioned as "jumping to the hash chain which points to farther distance"? What's the fundamental difference between this one and the zlib behavior, which is keep checking ```p = prev[1000], p1 = prev[p], p2 = prev[p1]```?

My questions might be too long, but I really want to understand this algorithm better, and look forward to getting some feedback from you.

Thank you.

Euccas

**Comment by gildor2** [comment]
Hi Euccas,
Responded in a copy of your message at gildor.org forums:
http://www.gildor.org/smf/index.php/topic,774.0.html
Konstantin
