### ISSUE TITLE
Rebase to cloudflare's zlib branch

### ISSUE THREAD

**Issue by caoli5288** [gildor2/fast_zlib#5]
This repo is currently active and NOT compaiable with your patch:)
https://github.com/cloudflare/zlib

**Comment by gildor2** [comment]
My "patch" is intended to speedup original zlib code. Is "cloudflare" compatible with "zlib-ng"? I suppose not. So why my repo should be compatible with those two?

If you feel that my code works faster than cloudflare, why simply won't use it?

**Comment by caoli5288** [comment]
Seem cloudflare's faster than libz-ng(much) and yours faster than cloudflare's.
:)

**Comment by gildor2** [comment]
So, what's the point for merging my zlib with slower one? ;)

**Comment by caoli5288** [comment]
I means you can patch cloudflare's make it more faster :)

**Comment by gildor2** [comment]
Yesterday I looked in Internet about different "zlib forks". I see that they compete with each other - cloudflare, zlib-ng, intel, etc etc. If my version is faster, why can't I compete with them too? :)

Personally I'd prefer to see my code integrated into stock zlib, however Mark Adler seems get away from zlib support last year. But I still have a hope.

**Comment by caoli5288** [comment]
Yes. I think you can make new fork instead of an patched file:)

**Comment by gildor2** [comment]
There are ready-to-use files in "Releases" sections (for Windows). I see no point of making a fork when I just need to add one source file and use simple instructions for building the whole library. My code could be compiled with any zlib version (I think), and for any platform.

Really, if I'd like to improve other places of zlib later, I'd consider using fork - but at the moment it's really a kind of patch.

**Comment by caoli5288** [comment]
Look forward to more improvement. :)
