### ISSUE TITLE
Recommended compiling flags

### ISSUE THREAD

**Issue by yamaken93** [gildor2/fast_zlib#6]
Hey, @gildor2 thanks for the awesome code. I'm using zlib(boost iostreams) in a small game server to compress(deflate) the game packets and i want to know if this flags("CFLAGS="-march=native -O2" ./configure") are good enough for optimize zlib together with your C code.

**Comment by gildor2** [comment]
Hi. There's no special compiler flags for it. I simply use "optimize by speed" (-O2), so I think it matches your case.

**Comment by yamaken93** [comment]
@gildor2 thanks. 
Another subject: did you saw this https://github.com/madler/zlib/issues/360?

**Comment by gildor2** [comment]
Yes. That guy offers increasing hash table size. This might help, might not. If current hash table size is enough, then increasing it further will not speed up much, and in some cases even could slow-down (when code for maintaining large hash table will take too much time). Just imagine: you're compressing 10Kb file, and using 64k x 8 bytes (64k pointers) hash table for that.

Also that guy made a few mistakes., One of them is assumption that hash has 256 only items - this is true only for compression level 1, which is nearly no compression at all. For compression level 9, hash table uses 16 bits.

**Comment by yamaken93** [comment]
@gildor2 thanks for the answers. You can close this issue.

**Comment by photopea** [comment]
@gildor2 There is no 64k x 8 bytes There is 32k x 2 bytes (64k bytes in total). DEFLATE can "refer backwards" only up to 32k bytes, and you need only 2-byte pointers to index it.

Also, ZLIB uses only 256-item table when tracking the string occurences, as it has 8-bit hashes.

**Comment by gildor2** [comment]
> @gildor2 There is no 64k x 8 bytes There is 32k x 2 bytes (64k bytes in total). DEFLATE can "refer backwards" only up to 32k bytes, and you need only 2-byte pointers to index it.
> 
Yes, my mistake. Perhaps I talked about "generic" hash table - I don't remember.

> Also, ZLIB uses only 256-item table when tracking the string occurences, as it has 8-bit hashes.
deflateInit2_ has the following code:
```
    s->hash_bits = (uInt)memLevel + 7;
    s->hash_size = 1 << s->hash_bits;
```
memLevel is initialized with DEF_MEM_LEVEL which is 8, so hash has 15 bits, not 8.

**Comment by photopea** [comment]
You are right. I think I mixed it up with decompression, where ZLIB uses two 8-bit hash tables (two level hashing). 

Also, I thought ZLIB can always run inside 64 kB of RAM, which would not be true in case of 16 hash bits.
